# fly.toml app configuration file generated for ama-b-viewer-long-mountain-8199 on 2025-04-22T21:58:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ama-b-viewer-long-mountain-8199'
primary_region = 'fra'

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_DEBUG = 'False'

[[services]]
  protocol = 'tcp'
  internal_port = 5000

  [[services.ports]]
    port = 80
    handlers = ['http']

[[vm]]
  size = 'shared-cpu-1x'
